name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # If no package.json, these steps safely skip
      - name: Install deps
        run: npm ci || npm i

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present
